FROM node:lts-bookworm-slim as build
ENV VITE_NODE_ENV $VITE_NODE_ENV
ENV VITE_YAMAP_API_KEY $VITE_YAMAP_API_KEY
ENV VITE_BACK_URL $VITE_BACK_URL
WORKDIR /app
COPY package*.json .
RUN npm i
RUN ECHO $VITE_NODE_ENV
RUN ECHO $VITE_YAMAP_API_KEY
RUN ECHO $VITE_BACK_URL
COPY . .
RUN npm run build